"""Add query_history table

Revision ID: 80641cb421d4
Revises: e40f74b7d6ab
Create Date: 2025-11-12 22:09:54.496964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80641cb421d4'
down_revision = 'e40f74b7d6ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
