"""Initial migration

Revision ID: e40f74b7d6ab
Revises: 
Create Date: 2025-11-12 20:44:14.472325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e40f74b7d6ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Company/organization name'),
    sa.Column('subdomain', sa.String(length=100), nullable=True, comment="Optional custom subdomain (e.g., 'alza' -> alza.wilco.cz)"),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Tenant is active and can access platform'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant this user belongs to'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email (login identifier)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full name"),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='User can login and access system'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='User has admin privileges'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Last successful login timestamp'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant that owns this dataset'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment="Internal filename (e.g., 'sales_uuid.csv')"),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment="Original uploaded filename (e.g., 'Sales.csv')"),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Path to stored file'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='SHA256 hash for deduplication'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('rows', sa.Integer(), nullable=True, comment='Number of rows in dataset'),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Column names and types: {"col1": "int64", "col2": "object"}'),
    sa.Column('dataset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata (date range, categories, etc.)'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='User who uploaded this dataset'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Last time this dataset was queried'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_tenant_id'), 'datasets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_datasets_uploaded_at'), 'datasets', ['uploaded_at'], unique=False)
    op.create_table('query_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant that executed this query'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who executed this query'),
    sa.Column('query_text', sa.Text(), nullable=False, comment="User's natural language query"),
    sa.Column('generated_code', sa.Text(), nullable=True, comment='Python/pandas code generated by Claude'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Query result as JSON (DataFrame.to_dict())'),
    sa.Column('result_rows', sa.Integer(), nullable=True, comment='Number of rows in result'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='Query execution time in milliseconds'),
    sa.Column('success', sa.Boolean(), nullable=True, comment='Query executed successfully'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if query failed'),
    sa.Column('datasets_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of dataset IDs used in this query'),
    sa.Column('context_query_id', sa.UUID(), nullable=True, comment='Previous query ID if this is a follow-up'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_created_at'), 'query_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_history_tenant_id'), 'query_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_history_user_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_tenant_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_created_at'), table_name='query_history')
    op.drop_table('query_history')
    op.drop_index(op.f('ix_datasets_uploaded_at'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_tenant_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
