"""
QueryHistory Model
Track all queries executed by users
"""

from sqlalchemy import Column, String, DateTime, Integer, Boolean, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.db.session import Base


class QueryHistory(Base):
    """
    Query History model
    
    Tracks all queries executed via the platform:
    - User's natural language query
    - Generated Python code
    - Results
    - Execution time
    - Success/failure
    """
    
    __tablename__ = "query_history"
    
    # ==========================================
    # COLUMNS
    # ==========================================
    
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    
    tenant_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Tenant that executed this query"
    )
    
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="User who executed this query"
    )
    
    query_text = Column(
        Text,
        nullable=False,
        comment="User's natural language query"
    )
    
    generated_code = Column(
        Text,
        nullable=True,
        comment="Python/pandas code generated by Claude"
    )
    
    result = Column(
        JSONB,
        nullable=True,
        comment="Query result as JSON (DataFrame.to_dict())"
    )
    
    result_rows = Column(
        Integer,
        nullable=True,
        comment="Number of rows in result"
    )
    
    execution_time_ms = Column(
        Integer,
        nullable=True,
        comment="Query execution time in milliseconds"
    )
    
    success = Column(
        Boolean,
        default=True,
        comment="Query executed successfully"
    )
    
    error_message = Column(
        Text,
        nullable=True,
        comment="Error message if query failed"
    )
    
    datasets_used = Column(
        JSONB,
        nullable=True,
        comment="List of dataset IDs used in this query"
    )
    
    context_query_id = Column(
        UUID(as_uuid=True),
        nullable=True,
        comment="Previous query ID if this is a follow-up"
    )
    
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )
    
    # ==========================================
    # RELATIONSHIPS
    # ==========================================
    
    tenant = relationship(
        "Tenant",
        back_populates="queries"
    )
    
    user = relationship(
        "User",
        back_populates="queries"
    )
    
    # ==========================================
    # METHODS
    # ==========================================
    
    def __repr__(self):
        return f"<QueryHistory(id={self.id}, user_id={self.user_id})>"
    
    def to_dict(self, include_code=False, include_result=False):
        """
        Convert to dictionary
        
        Args:
            include_code: Include generated Python code
            include_result: Include full result data
        """
        data = {
            "id": str(self.id),
            "tenant_id": str(self.tenant_id),
            "user_id": str(self.user_id),
            "query_text": self.query_text,
            "result_rows": self.result_rows,
            "execution_time_ms": self.execution_time_ms,
            "success": self.success,
            "error_message": self.error_message,
            "datasets_used": self.datasets_used,
            "context_query_id": str(self.context_query_id) if self.context_query_id else None,
            "created_at": self.created_at.isoformat() if self.created_at else None
        }
        
        if include_code:
            data["generated_code"] = self.generated_code
        
        if include_result:
            data["result"] = self.result
        
        return data
